# Generated by Django 5.1.6 on 2025-04-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='establised_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
