# Generated by Django 5.1.6 on 2025-02-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0002_alter_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="exp_need",
            field=models.IntegerField(default=0),
        ),
    ]
