# Generated by Django 5.1.6 on 2025-04-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_profile_establised_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
