# Generated by Django 5.1.6 on 2025-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_profile_total_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
