# Generated by Django 5.1.6 on 2025-02-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobseeker",
            "0006_profile_jobpreference_experience_education_resume_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, default="present", null=True),
        ),
    ]
