# Generated by Django 5.1.6 on 2025-02-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0007_alter_experience_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
