# Generated by Django 5.1.6 on 2025-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0009_alter_profile_about_me_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="exp_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
