# Generated by Django 5.1.6 on 2025-02-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0010_experience_exp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="id",
        ),
        migrations.AlterField(
            model_name="experience",
            name="exp_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
