# Generated by Django 5.1.6 on 2025-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0011_remove_experience_id_alter_experience_exp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="id",
        ),
        migrations.AddField(
            model_name="education",
            name="edu_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
