# Generated by Django 5.1.6 on 2025-02-19 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employer", "0001_initial"),
        ("jobseeker", "0012_remove_education_id_education_edu_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employer.company"
            ),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
