# Generated by Django 5.1.6 on 2025-02-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0013_alter_job_company_delete_company"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
