# Generated by Django 5.1.6 on 2025-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
