# Generated by Django 5.1.6 on 2025-02-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="Uid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
