# Generated by Django 5.1.6 on 2025-02-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="Uid",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
