# Generated by Django 5.1.6 on 2025-02-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_uid_alter_customuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("waiting", "Waiting")],
                default="waiting",
                max_length=50,
            ),
        ),
    ]
