# Generated by Django 5.1.6 on 2025-02-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("logo", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
