# Generated by Django 5.1.6 on 2025-02-19 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full-Time", "Full-Time"),
                            ("Part-Time", "Part-Time"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("salary_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salary_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("applications", models.IntegerField(default=0)),
                ("exp_need", models.IntegerField(default=0)),
                ("description", models.TextField()),
                ("responsibilities", models.TextField()),
                ("requirements", models.TextField()),
                ("benefits", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employer.company",
                    ),
                ),
            ],
        ),
    ]
