# Generated by Django 5.1.6 on 2025-02-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('closed', 'Closed')], default='draft', max_length=10),
        ),
    ]
