# Generated by Django 5.1.6 on 2025-02-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Closed', 'Closed')], default='draft', max_length=10),
        ),
    ]
