# Generated by Django 5.1.6 on 2025-03-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='id_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
