# Generated by Django 5.1.6 on 2025-03-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_remove_interview_candidate_remove_interview_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='job',
        ),
    ]
