# Generated by Django 5.1.6 on 2025-03-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_remove_interview_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='appication',
            new_name='application',
        ),
    ]
