# Generated by Django 5.1.6 on 2025-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_rename_appication_interview_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
