# Generated by Django 5.1.6 on 2025-03-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_jobapplication_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_interviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
