# Generated by Django 5.1.6 on 2025-03-27 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_jobapplication_is_interviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='resume_ratings',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
