# Generated by Django 5.1.6 on 2025-03-27 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0018_interview_communication_score_interview_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='resume_ratings',
            field=models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
