# Generated by Django 5.1.6 on 2025-03-27 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0019_alter_interview_resume_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='resume_ratings',
            field=models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
